"use client";
import "../sass/App.sass";
import "../sass/index.sass";

import { Inter } from "next/font/google";
import MuiTheme from "./MuiTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MuiTheme>{children}</MuiTheme>
      </body>
    </html>
  );
}
